version: '3'

services:
  pgsql:
    image: postgres:11-alpine
    ports:
      - '5434:5432'
    container_name: 'pg_microsservico'
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pg_microsservico

  msql:
    image: mysql
    ports:
      - '3306:3306'
    container_name: 'mys_microsservico'
    restart: always
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mys_microsservico
      MYSQL_ROOT_PASSWORD: mypassword

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always

volumes:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local

networks:
  default:
    name: nest_msg_network
